version: "3"

services:
  application:
    image: hello-docker-db:v1
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      - springboot-db-net
    volumes:
      - /data/springboot-app

  mysqldb:
    image: mysql:8
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=products
    volumes:
      - /data/mysql

networks:
  springboot-db-net:


